
version: 2

source:
  - name: sandbox
    schema: public
    tables:
      - name: omie_energy_buy
      - name: omie_price_hour


models:
  - name: energy_budget
    description: "energy demand times price"
