
version: 2

sources:
  - name: odoo
    schema: public
    tables:
      - name: airbyte_odoo_hr_employee
      - name: airbyte_odoo_hr_department
      - name: airbyte_odoo_hr_employee_calendar


models:
  - name: active_employees
    description: "list all employees active and with an active contract calendar interval"
